controllers_main:
    resource: ../../src/MainBundle/Controller/
    type: annotation

controllers_api:
    resource: ../../src/ApiBundle/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
